server:
  port: 8091
spring:
  application:
    name: App-One
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/mss_auth
    username: root
    password: root
jwt:
  secret: miraclesoft